name: Run all container database tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      id: build_jdk
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: build distribution
      env:
        MAVEN_CONFIG: "-B -fae"
      run: |
        make install-fast

    - name: run container tests
      env:
        MAVEN_CONFIG: "-B -fae"
      run: |
        make tests-container
