---
name: Run all container database tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  containers:
    name: Run testcontainer based tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-version: [ 1.18.3, 1.19.0 ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: build distribution
        env:
          MAVEN_CONFIG: "-B -fae"
        run: |
          make install-fast

      - name: run container tests
        env:
          MAVEN_CONFIG: "-B -fae -Ddep.testcontainers.version=${{ matrix.test-version }}"
        run: |
          make run-tests-container
