name: Code style checks

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      id: baseline_java
      with:
        java-version: 17
        distribution: temurin
    - name: style
      run: |
          ./src/build/gh-action-style.sh
