name: Test dependency versions

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  guava:
    name: Test Guava versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-version: [ 31.1-jre, 31.0.1-jre, 30.1.1-jre ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      id: setup_jdk
      name: Setup JDK
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Build
      run: |
          ./mvnw -B -fae -am -pl :jdbi3-guava,:jdbi3-guice -Ddep.guava.version=${{ matrix.test-version }} clean install

  immutables:
    name: Test Immutables versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-version: [ 2.9.0, 2.8.9-ea-1, 2.8.8 ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      id: setup_jdk
      name: Setup JDK
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Build
      run: |
          ./mvnw -B -fae -am -pl :jdbi3-core -Ddep.immutables.version=${{ matrix.test-version }} clean install

  jackson2:
    name: Test Jackson Versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-version: [ 2.13.3, 2.12.7, 2.11.4 ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      id: setup_jdk
      name: Setup JDK
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Build
      run: |
          ./mvnw -B -fae -am -pl :jdbi3-jackson2 -Ddep.jackson2.version=${{ matrix.test-version }} clean install

  jodatime2:
    name: Test joda-time versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-version: [ 2.10.14, 2.9.9 ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      id: setup_jdk
      name: Setup JDK
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Build
      run: |
          ./mvnw -B -fae -am -pl :jdbi3-jodatime2 -Ddep.joda-time.version=${{ matrix.test-version }} clean install

  vavr:
    name: Test vavr versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-version: [ 1.0.0-alpha-4, 0.10.4, 0.9.3 ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      id: setup_jdk
      name: Setup JDK
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Build
      run: |
          ./mvnw -B -fae -am -pl :jdbi3-vavr -Ddep.vavr.version=${{ matrix.test-version }} clean install
