name: Test dependency versions

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  guava:
    name: Test Guava versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-version: [ 31.1-jre, 30.1.1-jre ]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Build
      env:
        MAVEN_CONFIG: "-B -fae"
      run: |
        make install-fast

    - name: Test
      env:
        MAVEN_CONFIG: "-B -fae -pl :jdbi3-guava,:jdbi3-guice -Ddep.guava.version=${{ matrix.test-version }}"
      run: |
        make tests

  immutables:
    name: Test Immutables versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-version: [ 2.9.3, 2.9.2, 2.8.9-ea-1 ]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Build
      env:
        MAVEN_CONFIG: "-B -fae"
      run: |
        make install-fast

    - name: Test
      env:
        MAVEN_CONFIG: "-B -fae -pl :jdbi3-core -Ddep.immutables.version=${{ matrix.test-version }}"
      run: |
        make tests

  jackson2:
    name: Test Jackson Versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-version: [ 2.15.0-rc1, 2.14.2, 2.13.5, 2.12.7, 2.11.4 ]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Build
      env:
        MAVEN_CONFIG: "-B -fae"
      run: |
        make install-fast

    - name: Test
      env:
        MAVEN_CONFIG: "-B -fae -pl :jdbi3-jackson2 -Ddep.jackson2.version=${{ matrix.test-version }}"
      run: |
        make tests

  jodatime2:
    name: Test joda-time versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-version: [ 2.12.2, 2.11.2, 2.10.14 ]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Build
      env:
        MAVEN_CONFIG: "-B -fae"
      run: |
        make install-fast

    - name: Test
      env:
        MAVEN_CONFIG: "-B -fae -pl :jdbi3-jodatime2 -Ddep.joda-time.version=${{ matrix.test-version }}"
      run: |
        make tests

  vavr:
    name: Test vavr versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-version: [ 0.10.4 ]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Build
      env:
        MAVEN_CONFIG: "-B -fae"
      run: |
        make install-fast

    - name: Test
      env:
        MAVEN_CONFIG: "-B -fae -pl :jdbi3-vavr -Ddep.vavr.version=${{ matrix.test-version }}"
      run: |
        make tests

  guice:
    name: Test guice versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-version: [ 5.0.1, 5.1.0, 6.0.0, 7.0.0 ]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Build
      env:
        MAVEN_CONFIG: "-B -fae"
      run: |
        make install-fast

    - name: Test
      env:
        MAVEN_CONFIG: "-B -fae -pl :jdbi3-guice -Ddep.guice.version=${{ matrix.test-version }}"
      run: |
        make tests

  kotlin:
    name: Test kotlin runtime versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-version: [ 1.5.32, 1.6.21, 1.7.21, 1.8.21 ]

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: maven

    - name: Build
      env:
        MAVEN_CONFIG: "-B -fae"
      run: |
        make install-fast

    - name: Test
      env:
        MAVEN_CONFIG: "-B -fae -pl :jdbi3-kotlin,:jdbi3-kotlin-sqlobject -Ddep.kotlin.version=${{ matrix.test-version }}"
      run: |
        make tests
